rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  position_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2

  velocity_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2

  gains:
    joint1: {p: 10,  d: 1, i: 1, i_clamp: 1.5} 
    joint2: {p: 10,  d: 1, i: 1, i_clamp: 1.5} 
    velocity_ff:
    joint1: 1.0
    joint2: 1.0 

  effort controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2

  gains:
    joint1: {p: 100,  d: 1, i: 1, i_clamp: 2}
    joint2: {p: 100,  d: 1, i: 1, i_clamp: 2}  